{
  "formatVersion": "1.1",
  "component": {
    "group": "com.peak885",
    "module": "LibGuiForgified",
    "version": "0.1.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "LibGuiForgified-0.1.2+1.21.1.jar",
          "url": "LibGuiForgified-0.1.2+1.21.1.jar",
          "size": 602817,
          "sha512": "1c0cbb127325885d71829c7d2d8b62d4681fe1b0251cd0cbdb8cba8d35896db8165f94d3f04bdc098b8a1b0620506fd2edd73ccda2f9e099cb5f108eb541a280",
          "sha256": "2664e40ec9bd4dda7d1aba3502cd512a35e17bc6be58a29f00815c9ce1990fc1",
          "sha1": "a60b0f774b19ea539c89d3bac50c02f4dc7935be",
          "md5": "03977706bdf70e20398fb61b0a9a59c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.1-52.1.0_mapped_parchment_2024.11.17-1.21.1"
          }
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.TexBlock",
          "module": "LibNinePatch",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "LibGuiForgified-0.1.2+1.21.1.jar",
          "url": "LibGuiForgified-0.1.2+1.21.1.jar",
          "size": 602817,
          "sha512": "1c0cbb127325885d71829c7d2d8b62d4681fe1b0251cd0cbdb8cba8d35896db8165f94d3f04bdc098b8a1b0620506fd2edd73ccda2f9e099cb5f108eb541a280",
          "sha256": "2664e40ec9bd4dda7d1aba3502cd512a35e17bc6be58a29f00815c9ce1990fc1",
          "sha1": "a60b0f774b19ea539c89d3bac50c02f4dc7935be",
          "md5": "03977706bdf70e20398fb61b0a9a59c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "LibGuiForgified-0.1.2+1.21.1-sources.jar",
          "url": "LibGuiForgified-0.1.2+1.21.1-sources.jar",
          "size": 267207,
          "sha512": "0c95033a61b7cdc14937ba4bb5d97b6ce573ae64a786e15b4846eea6a5459c6aa05cea183b27f0c88f17e03f1fc8189d896b0f81181b1324f71691ae14e465c1",
          "sha256": "f86fa265fa2ae2c3602b02e6ceec4f91c0d6a371486b9678e730371cce2a0d02",
          "sha1": "41802e60c0dfca92983a07e41ceb273cef9b0c7f",
          "md5": "05ccfbf8f5280e1222c798ceae012b49"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "LibGuiForgified-0.1.2+1.21.1.jar",
          "url": "LibGuiForgified-0.1.2+1.21.1.jar",
          "size": 602817,
          "sha512": "1c0cbb127325885d71829c7d2d8b62d4681fe1b0251cd0cbdb8cba8d35896db8165f94d3f04bdc098b8a1b0620506fd2edd73ccda2f9e099cb5f108eb541a280",
          "sha256": "2664e40ec9bd4dda7d1aba3502cd512a35e17bc6be58a29f00815c9ce1990fc1",
          "sha1": "a60b0f774b19ea539c89d3bac50c02f4dc7935be",
          "md5": "03977706bdf70e20398fb61b0a9a59c2"
        }
      ]
    }
  ]
}
