{
  "formatVersion": "1.1",
  "component": {
    "group": "com.peak885",
    "module": "LibGuiForgified",
    "version": "0.1.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "LibGuiForgified-0.1.2+1.21.1.jar",
          "url": "LibGuiForgified-0.1.2+1.21.1.jar",
          "size": 602838,
          "sha512": "db8eecfe41546e240d7c8028415507d7ae9c90701f327e954e5f3f14ad8a8ed69aefbef50d6e61b3c9d4f5844fb63405955d56a36a83de74f62e149d4270a7bc",
          "sha256": "e13601667991bb1285249ecf3f9168a207e115f91226c33c1ee60530011c0d03",
          "sha1": "19213922373491905aad3487b318ce3259d0ee68",
          "md5": "c4d7ef3c1688008df2be9313cd9fcd2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.1-52.1.0_mapped_parchment_2024.11.17-1.21.1"
          }
        },
        {
          "group": "blue.endless",
          "module": "jankson",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.github.TexBlock",
          "module": "LibNinePatch",
          "version": {
            "requires": "master-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "LibGuiForgified-0.1.2+1.21.1.jar",
          "url": "LibGuiForgified-0.1.2+1.21.1.jar",
          "size": 602838,
          "sha512": "db8eecfe41546e240d7c8028415507d7ae9c90701f327e954e5f3f14ad8a8ed69aefbef50d6e61b3c9d4f5844fb63405955d56a36a83de74f62e149d4270a7bc",
          "sha256": "e13601667991bb1285249ecf3f9168a207e115f91226c33c1ee60530011c0d03",
          "sha1": "19213922373491905aad3487b318ce3259d0ee68",
          "md5": "c4d7ef3c1688008df2be9313cd9fcd2a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "LibGuiForgified-0.1.2+1.21.1-sources.jar",
          "url": "LibGuiForgified-0.1.2+1.21.1-sources.jar",
          "size": 267232,
          "sha512": "73e39b83deeed82452aaa3ca8e25c0683feb467553c2f4b48e1f5c440197e57ef0bb9a0b88c18ebd1287437fa4f59ac20ffc0b67df9610ea4a7381e206fdb800",
          "sha256": "f4ce6870bc1161eea8e9f9f9904b0f4523915cd8c29a58578b39ae41961b8e4a",
          "sha1": "913f696546cbb75a19c93a2e9048718278b34cdf",
          "md5": "1639fdfe725f76c6b9896648c53b84be"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "LibGuiForgified-0.1.2+1.21.1.jar",
          "url": "LibGuiForgified-0.1.2+1.21.1.jar",
          "size": 602838,
          "sha512": "db8eecfe41546e240d7c8028415507d7ae9c90701f327e954e5f3f14ad8a8ed69aefbef50d6e61b3c9d4f5844fb63405955d56a36a83de74f62e149d4270a7bc",
          "sha256": "e13601667991bb1285249ecf3f9168a207e115f91226c33c1ee60530011c0d03",
          "sha1": "19213922373491905aad3487b318ce3259d0ee68",
          "md5": "c4d7ef3c1688008df2be9313cd9fcd2a"
        }
      ]
    }
  ]
}
