{
  "formatVersion": "1.1",
  "component": {
    "group": "com.peak885.peakytoolkit",
    "module": "peakytoolkit",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "peakytoolkit-1.0.0-all.jar",
          "url": "peakytoolkit-1.0.0-all.jar",
          "size": 1360328,
          "sha512": "32c28e1772f358fee1b48327112391fa658105c5c0847d573b9b338b9f97c2deb03792ce2f10f5f522e07945fc25eb01b8785cae8499c814ede0f74caccdffe2",
          "sha256": "7df1e3271b78731832734da6ead5832cb64f96be5b278c93637ffedfac380aec",
          "sha1": "6e372e0f7ce3a522bbe51713a7c44efb8024c016",
          "md5": "22e2f5d571b78173b0ac5f74afcf0b4b"
        }
      ]
    }
  ]
}
