{
  "formatVersion": "1.1",
  "component": {
    "group": "com.peak885.blendin",
    "module": "blendin",
    "version": "1.0.0-forge-1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "blendin-1.0.0-forge-1.21.1-slim.jar",
          "url": "blendin-1.0.0-forge-1.21.1-slim.jar",
          "size": 814086,
          "sha512": "9e6e202bd7167df20a26a70ff233159f831bd030ad74b92c953f3b63658f1f8d7684401f96d8213d8b0e5c9eaea82a9f6c195e7a3152adf2380ddd0d9ff9a506",
          "sha256": "0a3672b542128a32575090ea26c2281d34b3ec7d466d85799333997bd1909f17",
          "sha1": "56498c6463ec011f84a57e03bf0d9e6ee94e8401",
          "md5": "d20725606b3df708d95f2923496b2cc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "strictly": "5.0.4",
            "requires": "5.0.4"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.1-52.1.0_mapped_parchment_2024.11.17-1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "blendin-1.0.0-forge-1.21.1-slim.jar",
          "url": "blendin-1.0.0-forge-1.21.1-slim.jar",
          "size": 814086,
          "sha512": "9e6e202bd7167df20a26a70ff233159f831bd030ad74b92c953f3b63658f1f8d7684401f96d8213d8b0e5c9eaea82a9f6c195e7a3152adf2380ddd0d9ff9a506",
          "sha256": "0a3672b542128a32575090ea26c2281d34b3ec7d466d85799333997bd1909f17",
          "sha1": "56498c6463ec011f84a57e03bf0d9e6ee94e8401",
          "md5": "d20725606b3df708d95f2923496b2cc8"
        }
      ]
    }
  ]
}
