{
  "formatVersion": "1.1",
  "component": {
    "group": "ladysnake.satin.Satin",
    "module": "satin",
    "version": "1.21.1-Forge+1.15.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "satin-1.21.1-Forge+1.15.0-SNAPSHOT-slim.jar",
          "url": "satin-1.21.1-Forge+1.15.0-SNAPSHOT-slim.jar",
          "size": 83727,
          "sha512": "b77b9e63307e42d017631552551f75781c2851f625b2cf0a7dc5593bdd62791b3aca0d174ede25ca819712ed133f1b42ba87e28e707667d24f52d70ab389223d",
          "sha256": "fc2f6d377fd103373dc47aa766a489736e0e56b9d6437670acf4c2363466a301",
          "sha1": "d792a5eeb8f978876205ab8e7dfbbf2e0bf291fb",
          "md5": "95cf43e70b627d643872762374c522ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-forge",
          "version": {
            "requires": "[0.3.5, 10.0.0)"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "strictly": "5.0.4",
            "requires": "5.0.4"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.21.1-52.1.0_mapped_parchment_2024.11.17-1.21.1_at_0497619d48a0dc2a2eadf9b923e468384bf49615"
          }
        }
      ],
      "files": [
        {
          "name": "satin-1.21.1-Forge+1.15.0-SNAPSHOT-slim.jar",
          "url": "satin-1.21.1-Forge+1.15.0-SNAPSHOT-slim.jar",
          "size": 83727,
          "sha512": "b77b9e63307e42d017631552551f75781c2851f625b2cf0a7dc5593bdd62791b3aca0d174ede25ca819712ed133f1b42ba87e28e707667d24f52d70ab389223d",
          "sha256": "fc2f6d377fd103373dc47aa766a489736e0e56b9d6437670acf4c2363466a301",
          "sha1": "d792a5eeb8f978876205ab8e7dfbbf2e0bf291fb",
          "md5": "95cf43e70b627d643872762374c522ec"
        }
      ]
    }
  ]
}
